### ISSUE TITLE
Student login Clinic not saving

### ISSUE THREAD

**Issue by mich2168** [ThinkHub-io/coeus-issues#7]
When student login to generate a new clinic session, it no longer saves.
![untitled](https://user-images.githubusercontent.com/46806526/51421317-82546b80-1bd7-11e9-86b0-e2a7140422f8.png)

**Comment by mrfrase3** [comment]
Found the issue, surprised it wasn't coming up earlier, should be fixed now.

**Comment by mich2168** [comment]
Hmm... tried to amend one of the pending grades - the one that was just created - by clicking radiographic technique, then save. Still shows up as unknown error... But, creating a new session from students and amendments from tutors is now possible. Thanks! So, only if a student is trying to add a step after clicking save or amend a pending procedure, then the error occurs.

**Comment by mrfrase3** [comment]
sorry, forgot to comment, I had found another issue and fixed it a while ago.
